# Generated by Django 5.2 on 2025-04-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('squash', 'Squash Court'), ('gym', 'Gym'), ('pool', 'Swimming Pool'), ('partyroom', 'Party Room'), ('tenniscourt', 'Tennis Court'), ('basketballcourt', 'Basketball Court')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('maxOccupancy', models.IntegerField(default=10)),
            ],
        ),
    ]
