# Generated by Django 5.2 on 2025-04-30 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facility_Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_images/')),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Facility_Booking.facility')),
            ],
        ),
    ]
